const injectionsites =[
  { part: 'Thigh', side: 'left', quadrant: 1, active: true, imgNum: 0 },
  { part: 'Thigh', side: 'left', quadrant: 2, active: true, imgNum: 1 },
  { part: 'Thigh', side: 'left', quadrant: 3, active: true, imgNum: 2 },
  { part: 'Thigh', side: 'left', quadrant: 4, active: true, imgNum: 3 },
  { part: 'Thigh', side: 'right', quadrant: 1, active: true, imgNum: 4 },
  { part: 'Thigh', side: 'right', quadrant: 2, active: true, imgNum: 5 },
  { part: 'Thigh', side: 'right', quadrant: 3, active: true, imgNum: 6 },
  { part: 'Thigh', side: 'right', quadrant: 4, active: true, imgNum: 7 },
  { part: 'Hip', side: 'left', quadrant: 1, active: true, imgNum: 8 },
  { part: 'Hip', side: 'left', quadrant: 2, active: true, imgNum: 9 },
  { part: 'Hip', side: 'left', quadrant: 3, active: true, imgNum: 10 },
  { part: 'Hip', side: 'left', quadrant: 4, active: true, imgNum: 11 },
  { part: 'Hip', side: 'right', quadrant: 1, active: true, imgNum: 12 },
  { part: 'Hip', side: 'right', quadrant: 2, active: true, imgNum: 13 },
  { part: 'Hip', side: 'right', quadrant: 3, active: true, imgNum: 14 },
  { part: 'Hip', side: 'right', quadrant: 4, active: true, imgNum: 15 },
  { part: 'Abdomen', side: 'left', quadrant: 1, active: true, imgNum: 16 },
  { part: 'Abdomen', side: 'left', quadrant: 2, active: true, imgNum: 17 },
  { part: 'Abdomen', side: 'left', quadrant: 3, active: true, imgNum: 18 },
  { part: 'Abdomen', side: 'left', quadrant: 4, active: true, imgNum: 19 },
  { part: 'Abdomen', side: 'right', quadrant: 1, active: true, imgNum: 20 },
  { part: 'Abdomen', side: 'right', quadrant: 2, active: true, imgNum: 21 },
  { part: 'Abdomen', side: 'right', quadrant: 3, active: true, imgNum: 22 },
  { part: 'Abdomen', side: 'right', quadrant: 4, active: true, imgNum: 23 },
  { part: 'Arm', side: 'left', quadrant: 1, active: true, imgNum: 24 },
  { part: 'Arm', side: 'left', quadrant: 2, active: true, imgNum: 25 },
  { part: 'Arm', side: 'left', quadrant: 3, active: true, imgNum: 26 },
  { part: 'Arm', side: 'left', quadrant: 4, active: true, imgNum: 27 },
  { part: 'Arm', side: 'right', quadrant: 1, active: true, imgNum: 28 },
  { part: 'Arm', side: 'right', quadrant: 2, active: true, imgNum: 29 },
  { part: 'Arm', side: 'right', quadrant: 3, active: true, imgNum: 30 },
  { part: 'Arm', side: 'right', quadrant: 4, active: true, imgNum: 31 },
  { part: 'Buttocks', side: 'left', quadrant: 1, active: true, imgNum: 32 },
  { part: 'Buttocks', side: 'left', quadrant: 2, active: true, imgNum: 33 },
  { part: 'Buttocks', side: 'left', quadrant: 3, active: true, imgNum: 34 },
  { part: 'Buttocks', side: 'left', quadrant: 4, active: true, imgNum: 35 },
  { part: 'Buttocks', side: 'right', quadrant: 1, active: true, imgNum: 36 },
  { part: 'Buttocks', side: 'right', quadrant: 2, active: true, imgNum: 37 },
  { part: 'Buttocks', side: 'right', quadrant: 3, active: true, imgNum: 38 },
  { part: 'Buttocks', side: 'right', quadrant: 4, active: true, imgNum: 39 }
];

export default injectionsites;
