const injectionsites = [
  "Left Thigh(1)",
  "Left Thigh(2)",
  "Left Thigh(3)",
  "Left Thigh(4)",
  "Right Thigh(1)",
  "Right Thigh(2)",
  "Right Thigh(3)",
  "Right Thigh(4)",
  "Left Hip(1)",
  "Left Hip(2)",
  "Left Hip(3)",
  "Left Hip(4)",
  "Right Hip(1)",
  "Right Hip(2)",
  "Right Hip(3)",
  "Right Hip(4)",
  "Left Abdomen(1)",
  "Left Abdomen(2)",
  "Left Abdomen(3)",
  "Left Abdomen(4)",
  "Right Abdomen(1)",
  "Right Abdomen(2)",
  "Right Abdomen(3)",
  "Right Abdomen(4)",
  "Left Arm(1)",
  "Left Arm(2)",
  "Left Arm(3)",
  "Left Arm(4)",
  "Right Arm(1)",
  "Right Arm(2)",
  "Right Arm(3)",
  "Right Arm(4)",
  "Left Buttock(1)",
  "Left Buttock(2)",
  "Left Buttock(3)",
  "Left Buttock(4)",
  "Right Buttock(1)",
  "Right Buttock(2)",
  "Right Buttock(3)",
  "Right Buttock(4)"
];

export default injectionsites;
